#!/usr/bin/env sh

# Custom bspwm path
export PATH="$PATH:$HOME/.config/bspwm/bin"

##[Dual]Monitor---------------------------------------------------------------------------
export priMon=$(xrandr --query |grep -w "connected primary" |cut -d" " -f1)
extMon=$(xrandr --query |grep " connected " |sed '/primary/d' |cut -d" " -f1)
prevMon=$(xrandr --listactivemonitors |awk '/1:/{ print $4 }')

monitor() {
    if [[ -z $extMon ]]; then
    ##Single monitor
        ##Move window to desktop 5 from external monitor
        for node in $(bspc query -N -d Desktop -n .leaf); do
            bspc node $node -d '^5' --follow
        done
        ##Remove monitor
        bspc monitor $prevMon --remove
        xrandr  --output $prevMon --off
    else
    ##Dual monitor
        xrandr  --output $priMon --auto --primary --rotate normal --pos 0x0 \
                --output $extMon --auto --rotate normal --pos 1380x0
        bspc config -m $extMon top_padding 0
    fi
}

bspc monitor $priMon -d 1 2 3 4 5
monitor

##Bspwm config----------------------------------------------------------------------------
_borderWidth=2
top_padding=27
[ $(bspc config border_width) != $_borderWidth ] &&
    bspc config border_width    $_borderWidth

bspc config -m $priMon top_padding $top_padding
bspc config left_padding    0
bspc config right_padding   0
bspc config bottom_padding  0
bspc config window_gap      7
bspc config split_ratio     0.507

bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config ignore_ewmh_focus             false
bspc config ignore_ewmh_struts            false
bspc config remove_unplugged_monitors     true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config focus_follows_pointer         true
bspc config pointer_follows_monitor       true
bspc config directional_focus_tightness   low
bspc config automatic_scheme              alternate

bspc config pointer_modifier			        mod4
bspc config pointer_action1				        move
bspc config pointer_action2				        resize_side
bspc config pointer_action3				        resize_corner

#BSPWM coloring
bspc config normal_border_color		        "#272727"
bspc config active_border_color		        "#6fa12b"
bspc config focused_border_color	        "#e9b143"
bspc config presel_feedback_color	        "#a9b665"

#"#799eda" "#FD4A9C" "#8aea26"

##Autorun---------------------------------------------------------------------------------
[[ $(command -v autostart) ]] &&
    autostart &

##External rules, auto reload--------------------------------------------------------------
## Remove all previous rules first
bspc rule -r "*"
bspc config external_rules_command "$HOME/.config/bspwm/external_rules" &

##==================================external config========================================

##Set default state on specific desktop----------------------------------------------------
#Usage: default_desktop_state [desktop name] [tiled|pseudo_tiled|floating|fullscreen]
#default_desktop_state 5 pseudo_tiled &

## Picom Shadow only floating--------------------------------------------------------------
## add "!_COMPTON_SHADOW@:32c = 1" to shadow-exclude in picom config

bspc subscribe node_state | while read -r _ _ _ node state status; do
    if [[ $state == floating ]]; then
        case $status in
            off) xprop -id "$node" -remove _COMPTON_SHADOW;;
            on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
        esac
    fi
done

