#!/usr/bin/env sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"


#[Dual]Monitor
#-------------------------------------------------------------------------------------------------------------
#Find out names with arandr or xrandr
_primaryMonitor=$(xrandr --query | grep " connected primary" | cut -d" " -f1)
ext_mon_check=$(xrandr --query |grep " connected " |sed '/primary/d' |cut -d" " -f1)
log_file=$HOME/.cache/dual_monitor.log

    [[ -n $ext_mon_check ]] && echo $ext_mon_check > $log_file
ext_mon_name=$(cat $log_file)


dual_monitor () {
if
#check & enable dualmonitor
  [[ -n $ext_mon_check ]]; then
    xrandr --output VIRTUAL1 --off
    xrandr --output $_primaryMonitor --auto --primary --rotate normal --pos 0x0 --output $ext_mon_check --auto --rotate normal --below $_primaryMonitor
    bspc config-m $ext_mon_check top_padding 0
else
#close node[s] in externat_monitor when disconnect
  if
    [[ -n $(bspc query -N -d Desktop -n .leaf) ]]; then
      for node in $(bspc query -N -d Desktop -n .leaf)
      do
        bspc node $node -c
      done
  fi
#remove ext desktop && monitor
  bspc monitor $ext_mon_name --remove
  xrandr  --output $ext_mon_name --off
fi
}




#Run dualmonitor
[ -f $log_file ] && [ $(cat $log_file |wc -l) = 1 ] && dual_monitor
 
#Desktop primary monitor
bspc monitor $_primaryMonitor -d 1 2 3 4 5


#Autorun
#-----------------------------------------------------------------------------------------
[ -f $HOME/.xprofile ] &&
    . $HOME/.xprofile


#Bspwm config
#-----------------------------------------------------------------------------------------
#BSPWM configuration
_borderWidth=2
[ $(bspc config border_width) != $_borderWidth ] &&

bspc config border_width    $_borderWidth
bspc config window_gap      10
bspc config bottom_padding  0
bspc config left_padding    0
bspc config right_padding   0
bspc config split_ratio     0.507
bspc config -m $_primaryMonitor top_padding     20

bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config ignore_ewmh_focus             true
bspc config remove_unplugged_monitors     true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config focus_follows_pointer         true
bspc config pointer_follows_monitor       true
bspc config directional_focus_tightness   low
bspc config automatic_scheme              alternate

bspc config pointer_modifier			        mod4
bspc config pointer_action1				        move
bspc config pointer_action2				        resize_side
bspc config pointer_action3				        resize_corner

#BSPWM coloring
bspc config normal_border_color		        "#2d3718"
bspc config active_border_color		        "#6fa12b"
bspc config focused_border_color	        "#8aea26"
bspc config presel_feedback_color	        "#8fb758"
#bspc config urgent_border_color 	        "#dd2727"


#External rules, auto reload
#-------------------------------------------------------------------------------------------------------------
bspc config external_rules_command "$HOME/.config/bspwm/scripts/external_rules" &


#picom Shadow only floating
#-------------------------------------------------------------------------------------------------------------
#add "!_COMPTON_SHADOW@:32c = 1" to shadow-exclude in config
bspc subscribe node_state | while read -r _ _ _ node state status; do
    if [[ "$state" == "floating" ]]; then
        case "$status" in
            off) xprop -id "$node" -remove _COMPTON_SHADOW;;
            on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
        esac
    fi
done

